### ISSUE TITLE
New features suggestion

### ISSUE THREAD

**Issue by leisurecodog** [richardkuo1999/My_Stock_Page#1]
### Maybe could added a column for EPS input 
Sometime the crawl of EPS may get wrong value or get nothing, so can give user a column that can input their estimated EPS got from other source.
### More of stock can added to daily report
According to current nubmer of stock, it's about 200 for user picked, maybe can added other resouce can join to the daily report, such as 法人買賣超.

Thanks.

**Comment by richardkuo1999** [comment]
**Maybe could added a column for EPS input**
This feature can potentially be added at the individual searches, but daily searches cannot do this.

**More of stock can added to daily report**
This feature is achievable, but there are several issues that need to be resolved:
2. There may be issues with ETFs.
3. It is necessary to temporarily store an additional 200 records (currently none) to avoid duplicate searches.
4. Cancel weekend trading computations to prevent resource waste.
5. We need sponsorship from Dad Xie, as the current usage of 200 records on AWS has reached 90%, and the usage of this feature will exceed that."

Thanks your suggestion

**Comment by richardkuo1999** [comment]
### **Maybe could added a column for EPS input**

Ｍodify the [Individual_search](https://github.com/richardkuo1999/value_investment/blob/0b94852e405cfc4aa4acfa84d229823085300eef/server_main.py#L53) input
`def Individual_search(StockLists):  -> def Individual_search(StockLists, EPSLists):`

StockLists = ["2345", "2330", "2329", "2351", "6438"]
EPSLists = ["1.1", "2", "", "3.3", ""]

**Notice:**  Individual searches and  daily searches use same [calculator()](https://github.com/richardkuo1999/value_investment/blob/0b94852e405cfc4aa4acfa84d229823085300eef/calculator/calculator.py#L224)

**Comment by richardkuo1999** [comment]
@leisurecodog Please help to review the code

### Maybe could added a column for EPS input
https://github.com/richardkuo1999/value_investment/commit/6ae9528b27dec70b623c4af4d65b5cdf3a05d5f6
https://github.com/richardkuo1999/My_Stock_Page/commit/7556779a894ac7e02b4423e06f3f13c7de5363bf

Here is the test result [file](https://github.com/user-attachments/files/17493681/result_Individual.zip)
输入内容:  2345 2345 2345 2345
EPS(無請用 n): n 1.1 n 2.2


### > Don't try and error on the server

**Comment by richardkuo1999** [comment]
> **Maybe could added a column for EPS input** This feature can potentially be added at the individual searches, but daily searches cannot do this.
> 
> **More of stock can added to daily report** This feature is achievable, but there are several issues that need to be resolved: 2. There may be issues with ETFs. 3. It is necessary to temporarily store an additional 200 records (currently none) to avoid duplicate searches. 4. Cancel weekend trading computations to prevent resource waste. 5. We need sponsorship from Dad Xie, as the current usage of 200 records on AWS has reached 90%, and the usage of this feature will exceed that."
> 
> Thanks your suggestion

No.5 Is my mistake Global-BoxUsage:freetier.micro and Global-EBS:VolumeUsage **Not based on how much calculation I use**, So **More of stock can added to daily report**  is a function that can be added

**Comment by richardkuo1999** [comment]
More of stock can added to daily report
Already completed at [835c639](https://github.com/richardkuo1999/My_Stock_Page/commit/835c63913c4f41c13246c6afeff9f463b1812606) [eae6292](https://github.com/richardkuo1999/value_investment/commit/eae62927a122c075ae8c8110d90c75d363674410)
join 法人買賣超  to the daily report
