### ISSUE TITLE
Daily report improvement for faster review calculation result

### ISSUE THREAD

**Issue by leisurecodog** [richardkuo1999/My_Stock_Page#3]
The daily calculation is convenient, but maybe can dump the stock name or stock id when the price is **underestimated** ,
such as -1 STD for forward EPS or mean regression, thanks.

**Comment by richardkuo1999** [comment]
Hi @leisurecodog ,
This is a good idea

We can further discuss the criteria for determining whether something is "underestimated," as well as what additional information would be useful, such as target price, estimated EPS, and so on.

**Comment by richardkuo1999** [comment]
Hi @leisurecodog ,

This feature is done at [33cae1ed10faa8f35564b34e05b4fb2b6658c9b0](https://github.com/richardkuo1999/My_Stock_Page/commit/33cae1ed10faa8f35564b34e05b4fb2b6658c9b0)

Current use the -1 STD as a basis for underestimated
